/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client"

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export default function Curiosity(props) {
  const { nodes, materials } = useGLTF('/models/Curiosity-transformed.glb')

  const modelRef = useRef();
  useFrame(() => {
      modelRef.current.rotation.y += 0.007;
    });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      scale={[1.0, 1.0, 1.0]}
      rotation={[0.4, -1, 0]}
      position={[0, 0, 0]}
    >
      <mesh
        name="Object_163"
        castShadow
        receiveShadow
        geometry={nodes.Object_163.geometry}
        material={materials.tex_02}
        position={[0.322, 0.836, -0.312]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.679}
      />
      <mesh
        name="Object_85"
        castShadow
        receiveShadow
        geometry={nodes.Object_85.geometry}
        material={materials.tex_03}
        position={[0.307, 0.678, 0.756]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.679}
      />
      <mesh
        name="Object_87"
        castShadow
        receiveShadow
        geometry={nodes.Object_87.geometry}
        material={materials.tex_01}
        position={[0.307, 0.678, 0.756]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.679}
      />
      <mesh
        name="Object_97"
        castShadow
        receiveShadow
        geometry={nodes.Object_97.geometry}
        material={materials.tex_04}
        position={[0.304, 0.565, 0.864]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.679}
      />
      <mesh
        name="Object_99"
        castShadow
        receiveShadow
        geometry={nodes.Object_99.geometry}
        material={materials.tex_05}
        position={[0.304, 0.565, 0.864]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.679}
      />
      <mesh
        name="Object_144"
        castShadow
        receiveShadow
        geometry={nodes.Object_144.geometry}
        material={materials.white_LED}
        position={[0.147, 1.29, 1.263]}
        rotation={[-3.11, -0.992, -1.023]}
        scale={0.001}
      />
      <mesh
        name="Object_80"
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials['tex_01.001']}
        position={[0, 0.602, 0.037]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.679}
      />
      <mesh
        name="Object_82"
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        material={materials.parts_AO}
        position={[0, 0.602, 0.037]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.679}
      />
      <mesh
        name="Object_229"
        castShadow
        receiveShadow
        geometry={nodes.Object_229.geometry}
        material={materials.tex_03_n}
        position={[0.718, 0.165, -0.789]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.679}
      />
      <mesh
        name="Object_203"
        castShadow
        receiveShadow
        geometry={nodes.Object_203.geometry}
        material={materials['tex_03.002']}
        position={[0.435, 0.594, 0.145]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.679}
      />
    </group>
  )
}

useGLTF.preload('/models/Curiosity-transformed.glb')

