// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */
// "use client";
// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";
// import { useFrame } from "@react-three/fiber";

// const HatModel = React.memo(function HatModel(props) {
//   // Use React.memo for performance optimization
//   const { nodes, materials } = useGLTF("/models/hat-transformed.glb");

//   const modelRef = useRef();

//   useFrame(() => {
//     modelRef.current.rotation.y += 0.007;
//   });
//   return (
//     <group
//       {...props}
//       dispose={null}
//       ref={modelRef}
//       scale={[1.8, 1.8, 1.8]}
//       rotation={[0.4, -1, 0]}
//       position={[0, 0, 0]}
//     >
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_2.geometry}
//         material={materials.initialShadingGroup}
//         position={[0, -3.867, 0]}
//         rotation={[-Math.PI / 2, 0, 0]}
//       />
//     </group>
//   );
// });

// export default HatModel;
// useGLTF.preload("/models/hat-transformed.glb");



/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gustavo3010 (https://sketchfab.com/Gustavo3010)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-dog-gustavo-adolfo-f136e21247a3458981b3023212996d69
Title: Robot dog- Gustavo Adolfo
*/

"use client";
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export default function HatModel(props) {
  const { nodes, materials } = useGLTF('/models/robot_dog-transformed.glb')
  
  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });
  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      scale={[0.02, 0.02, 0.02]}
      rotation={[0.4, -1, 0]}
      position={[0, 2, 0]}
    >
      <mesh
        name="Object_2"
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.color_16768282}
        position={[0, -64.371, 33.941]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        name="Object_3"
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials.color_2829873}
        position={[0, -64.371, 33.941]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        name="Object_4"
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.color_6383466}
        position={[0, -64.371, 33.941]}
        rotation={[-Math.PI, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/robot_dog-transformed.glb')

